---
- name: Install HAProxy
  ansible.builtin.package:
    name: haproxy
    state: present
  become: true
- name: Add Certbot deploy hooks
  when: haproxy_certbot_certs is defined
  ansible.builtin.template:
    src: certbot-deploy-hook.sh.j2
    dest: "{{ haproxy_certbot_deploy_hook }}"
    owner: root
    group: root
    mode: '0755'
  vars:
    certs: "{{ haproxy_certbot_certs }}"
  become: true
  notify: HAProxy Certbot Deploy
- name: Create HAProxy configuration file from template
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Restart HAProxy
- name: Ensure HAProxy is running and enabled
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: true
  become: true
