---
- name: Install HAProxy
  ansible.builtin.package:
    name: haproxy
    state: present
  become: true

- name: Create HAProxy configuration file from template
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Restart HAProxy

- name: Ensure HAProxy is running and enabled
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: true
  become: true
