---
proxy_port: 8091
proxy_sso_enabled: true
reverseproxy_nginx_after:
  - network-online.target
  - zwave-js-ui.service
proxy_healthcheck:
  path: /health
  checks:
    - type: port
      value: "{{ proxy_port }}"
    - type: service
      value: zwave-js-ui
