---
- name: Apt update
  ansible.builtin.apt:
    update_cache: true
  become: true
- name: Reload udev rules
  ansible.builtin.command:
    cmd: /usr/bin/udevadm control --reload
  changed_when: true
  become: true
- name: Trigger udev rules
  ansible.builtin.command:
    cmd: /usr/bin/udevadm trigger --subsystem-match=pci
  changed_when: true
  become: true
