---
common_apt_cache_validity: 86400
common_apt_repo_updates_distros:
  Debian: true
  Ubuntu: true
common_apt_repo_security_distros:
  Debian: true
  Ubuntu: true
common_apt_repo_backports_distros:
  Debian: false
  Ubuntu: true
common_apt_repo_restricted_distros:
  Debian: false
  Ubuntu: true
common_apt_repo_universe_distros:
  Debian: false
  Ubuntu: true
common_apt_repo_multiverse_distros:
  Debian: false
  Ubuntu: true
common_apt_repo_contrib_distros:
  Debian: true
  Ubuntu: false
common_apt_repo_nonfreefirmware_distros:
  Debian: false
  Ubuntu: false
common_apt_repo_url_distros:
  Debian: http://deb.debian.org/debian
  Ubuntu: http://archive.ubuntu.com/ubuntu
common_apt_repo_security_url_distros:
  Debian: http://security.debian.org
  Ubuntu: http://archive.ubuntu.com/ubuntu
common_apt_repo_signing_key_distros:
  Debian: /usr/share/keyrings/debian-archive-keyring.gpg
  Ubuntu: /usr/share/keyrings/ubuntu-archive-keyring.gpg
common_join_ipa_domain: false
common_manage_etc_hosts: false
common_sshd_service_name_families:
  Debian: "ssh"
  RedHat: "sshd"

common_ssh_permit_root_login: "no"
common_ssh_password_authentication: "no"

common_ssh_ciphers:
  - "aes128-ctr"
  - "aes128-gcm@openssh.com"
  - "aes192-ctr"
  - "aes256-ctr"
  - "aes256-gcm@openssh.com"
common_ssh_kexalgorithms:
  - "curve25519-sha256@libssh.org"
  - "diffie-hellman-group-exchange-sha256"
  - "ecdh-sha2-nistp256"
  - "ecdh-sha2-nistp384"
  - "ecdh-sha2-nistp521"
common_ssh_macs:
  - "hmac-sha2-256"
  - "hmac-sha2-512"
  - "umac-128@openssh.com"
