---
- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present
  become: true
- name: Create Nginx Config file
  ansible.builtin.template:
    src: nginx.j2
    dest: /etc/nginx/sites-enabled/default
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Restart Nginx
- name: Create Web Directory
  ansible.builtin.file:
    path: /srv/ipxe_web/
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
- name: Default boot file
  ansible.builtin.copy:
    src: default.ipxe
    dest: /srv/ipxe_web/default.ipxe
    owner: www-data
    group: www-data
    mode: '0644'
- name: Start Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  become: true
