---
- name: Create tomcat group
  ansible.builtin.group:
    name: tomcat
    state: present
- name: Create tomcat user
  ansible.builtin.user:
    name: tomcat
    group: tomcat
    groups: guacamole
    append: true
    shell: /bin/false
    home: "{{ guacamole_tomcat_install_root }}"
    system: true
  notify: Restart Tomcat
- name: Create tomcat installation directory
  ansible.builtin.file:
    path: "{{ guacamole_tomcat_install_root }}"
    state: directory
    owner: tomcat
    group: tomcat
    mode: '0755'
- name: Download Apache Tomcat
  ansible.builtin.get_url:
    url: "{{ guacamole_tomcat_download_url }}"
    dest: "/tmp/apache-tomcat-{{ guacamole_tomcat_version }}.tar.gz"
    checksum: "{{ guacamole_tomcat_checksum }}"
    mode: '0644'
- name: Extract Apache Tomcat
  ansible.builtin.unarchive:
    src: "/tmp/apache-tomcat-{{ guacamole_tomcat_version }}.tar.gz"
    dest: /opt/
    remote_src: true
    owner: tomcat
    group: tomcat
    creates: "{{ guacamole_tomcat_install_root }}/bin/startup.sh"
- name: Download Guacamole web application
  ansible.builtin.get_url:
    url: "{{ guacamole_war_url }}"
    dest: "{{ guacamole_install_root }}/guacamole-{{ guacamole_version }}.war"
    checksum: "{{ guacamole_war_checksum }}"
    owner: guacamole
    group: guacamole
    mode: '0644'
- name: Link Guacamole web application to Tomcat ROOT
  ansible.builtin.file:
    src: "{{ guacamole_install_root }}/guacamole-{{ guacamole_version }}.war"
    dest: "{{ guacamole_tomcat_install_root }}/webapps/ROOT.war"
    state: link
    owner: tomcat
    group: tomcat
  notify:
    - Cleanup Exploded WARs
    - Restart Tomcat
- name: Deploy Tomcat server.xml
  ansible.builtin.template:
    src: server.xml.j2
    dest: "{{ guacamole_tomcat_install_root }}/conf/server.xml"
    owner: tomcat
    group: tomcat
    mode: '0640'
  notify: Restart Tomcat
- name: Deploy Tomcat systemd unit
  ansible.builtin.template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart Tomcat
- name: Deploy guacd systemd unit
  ansible.builtin.template:
    src: guacd.service.j2
    dest: /etc/systemd/system/guacd.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart guacd
