---
- name: Restart Mokey
  ansible.builtin.service:
    name: mokey
    state: restarted
  become: true
- name: Destroy kinit cache
  ansible.builtin.command:
    cmd: "kdestroy"
  changed_when: true
  become: true
