---
aws_creds_file_path: "/root/.aws/config"
users_delete_cloud_init_sudoers: true
users_manage_root: true
users_admins:
  - "brwyatt"
  - "localadmin"
users_list:
  brwyatt:
    password: "{{ brwyatt_password }}"
    ssh_pub_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDA3zFRckFN4FwVLOQOMzzW/VEquBskxUHj7olTrfRg2On8rCjURbvZXxofXzizuPC6v9hSc3qQhB4jJiVv67NJ3jzKNI7QuxwxNw0mPUknZvpF0tFepnIRJvUDLheXUO+UUM0EtX6Oi2f+C2b5+QRXufgFbjCB9JJIH3idDmesL1H+lRvwIBh2LWHn8OPh6ZmtmNhgWTMjtE8pueKSlBOS/QdzbWKqFFVU8xLJn8aNhgC7iTqygexYaW+ZdhGtzUikJy06lxzUqWq42dazLM9FJ107amZ0xA3tmdvVZIiuPbkqV1+gmFxfzzETLADOHOyX/swP12nwqwq/adv9663WgYUb5tWAU0SptRh8guVYGbB5elRfTPr0NglZrQPXotxc3PKRv8lmY9DRdv3VIwMKt1zFOqxX9CwJ+rRKhSGUy+Va8YHSc6Cbk4qhUygFJKkfWBdRdMkOsVVj3omSYANAdQeyYkBFVPk1WW+tgqGW/nTpsRnvknewjnuM0S+kaBRb0QvrYCzyAQmInkn4naWdDKjux1BbEaL3il+ZWeG53Sh/xXJcTUUxgBgw0lALrXYYyG8wheGu9ic2hiC6ubab2BZ67AJvknrjW7cm17jVVtmh9MFrhM37fXvnUnN91uTk31tzIo/v3qhuYizOzfe5CCqA1BQ9Yoqrdus7jw1YBQ== brwyatt"
  localadmin:
    password: "{{ localadmin_password }}"
    ssh_pub_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDA3zFRckFN4FwVLOQOMzzW/VEquBskxUHj7olTrfRg2On8rCjURbvZXxofXzizuPC6v9hSc3qQhB4jJiVv67NJ3jzKNI7QuxwxNw0mPUknZvpF0tFepnIRJvUDLheXUO+UUM0EtX6Oi2f+C2b5+QRXufgFbjCB9JJIH3idDmesL1H+lRvwIBh2LWHn8OPh6ZmtmNhgWTMjtE8pueKSlBOS/QdzbWKqFFVU8xLJn8aNhgC7iTqygexYaW+ZdhGtzUikJy06lxzUqWq42dazLM9FJ107amZ0xA3tmdvVZIiuPbkqV1+gmFxfzzETLADOHOyX/swP12nwqwq/adv9663WgYUb5tWAU0SptRh8guVYGbB5elRfTPr0NglZrQPXotxc3PKRv8lmY9DRdv3VIwMKt1zFOqxX9CwJ+rRKhSGUy+Va8YHSc6Cbk4qhUygFJKkfWBdRdMkOsVVj3omSYANAdQeyYkBFVPk1WW+tgqGW/nTpsRnvknewjnuM0S+kaBRb0QvrYCzyAQmInkn4naWdDKjux1BbEaL3il+ZWeG53Sh/xXJcTUUxgBgw0lALrXYYyG8wheGu9ic2hiC6ubab2BZ67AJvknrjW7cm17jVVtmh9MFrhM37fXvnUnN91uTk31tzIo/v3qhuYizOzfe5CCqA1BQ9Yoqrdus7jw1YBQ== brwyatt"
ansible_password: >-
  {{
    users_root_password
    if ansible_user == 'root'
    else (
      users_list[ansible_user].password
      if ansible_user in users_list
      else None
    )
  }}

chrony_sources:
  - type: "pool"
    location: "ntp.home.brwyatt.net"
    iburst: true
    trust: true
    prefer: true

common_join_ipa_domain: true

ipa_domain: "home.brwyatt.net"
ipa_realm: "{{ ipa_domain | upper }}"

ipaclient_domain: "{{ ipa_domain }}"
ipaclient_realm: "{{ ipa_realm }}"
ipaclient_mkhomedir: true

ipaadmin_principal: "ansible"

ipaserver_domain: "{{ ipa_domain }}"
ipaserver_realm: "{{ ipa_realm }}"
ipaservers: "{{ query('community.dns.lookup', '_ldap._tcp.' + ipaserver_domain + '.', type='SRV') | map('split') | map('last') | trim('.') }}"

ipareplica_domain: "{{ ipa_domain }}"
ipareplica_setup_ca: true
ipareplica_setup_dns: false
ipareplica_setup_firewalld: false
ipareplica_setup_kra: false
