---
- name: Install Ceph Common
  ansible.builtin.package:
    name: ceph-common
    state: present
  become: true
- name: Create Ceph Config file
  ansible.builtin.template:
    src: ceph.conf.j2
    dest: /etc/ceph/ceph.conf
    owner: root
    group: root
    mode: '0644'
  become: true
- name: Create Ceph Keyring
  ansible.builtin.template:
    src: keyring.j2
    dest: /etc/ceph/keyring
    owner: root
    group: root
    mode: '0600'
  become: true
- name: Create Mounts
  loop: "{{ cephclient_mounts }}"
  loop_control:
    loop_var: item
  ansible.builtin.include_tasks:
    file: mount.yml
