---
- name: Restart TFTPd
  ansible.builtin.service:
    name: tftpd-hpa
    state: restarted
  become: true
- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  become: true
