---
- name: Install Valkey
  ansible.builtin.package:
    name: valkey-server
    state: present
- name: Create Valkey config directory
  ansible.builtin.file:
    path: /etc/valkey
    state: directory
    owner: valkey
    group: valkey
    mode: '0755'
- name: Create Valkey certs directory
  ansible.builtin.file:
    path: /etc/valkey/certs
    state: directory
    owner: valkey
    group: valkey
    mode: '0750'
- name: Deploy Certbot renewal hook for Valkey
  ansible.builtin.template:
    src: valkey-cert-deploy.sh.j2
    dest: /etc/letsencrypt/renewal-hooks/deploy/valkey
    owner: root
    group: root
    mode: '0755'
  notify: Cert Deploy Hook
- name: Configure Valkey
  ansible.builtin.template:
    src: valkey.conf.j2
    dest: /etc/valkey/valkey.conf
    owner: valkey
    group: valkey
    mode: '0640'
  notify: Restart Valkey
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
- name: Ensure Valkey is started and enabled
  ansible.builtin.service:
    name: valkey-server
    state: started
    enabled: true
- name: Check Valkey Cluster state
  run_once: true
  delegate_to: "{{ groups['valkeyservers'][0] }}"
  ansible.builtin.command:
    cmd: >
      valkey-cli
      -u redis{{ "s" if valkey_tls else "" }}://admin:{{ valkey_admin_password }}@localhost:{{ valkey_port }}
      cluster info
  register: valkey_cluster_info
  changed_when: false
  failed_when: false
- name: Initialize Valkey Cluster
  run_once: true
  delegate_to: "{{ groups['valkeyservers'][0] }}"
  when: "'cluster_state:ok' not in valkey_cluster_info.stdout"
  changed_when: true
  ansible.builtin.command:
    cmd: >
      valkey-cli
      -u redis{{ "s" if valkey_tls else "" }}://admin:{{ valkey_admin_password }}@localhost:{{ valkey_port }}
      --cluster create
      {% for host in groups['valkeyservers'] %}
      {{ hostvars[host]['ansible_host'] | default(host) }}:{{ valkey_port }}
      {% endfor %}
      --cluster-replicas 0
      --cluster-yes
