---
shotover_version: "0.7.2"
shotover_checksum: "sha256:33359ffbdce1c1ed04cbb38d7776a771eb47c5b7b454dc40f9434bf8d1810077"
shotover_arch: "amd64"

shotover_install_root: "/opt/shotover"
shotover_version_dir: "{{ shotover_install_root }}/{{ shotover_version }}"
shotover_bin_path: "/usr/local/bin"

shotover_user: "shotover"
shotover_group: "shotover"

shotover_config_dir: "/etc/shotover"
shotover_topology_dir: "{{ shotover_config_dir }}/topology"

shotover_config:
  main_log_level: "info"
  observability_interface: "127.0.0.1:9001"

shotover_topology: {}
