---
shotover_install_root: "/opt/shotover"
shotover_bin_path: "/usr/local/bin"

shotover_user: "shotover"
shotover_group: "shotover"

shotover_config_dir: "/etc/shotover"
shotover_topology_dir: "{{ shotover_config_dir }}/topology"

shotover_config:
  main_log_level: "info"
  observability_interface: "127.0.0.1:9001"

shotover_topology: {}

shotover_custom_build_location: "localhost"
