---
- name: Check apt repo key
  ansible.builtin.stat:
    path: "{{ renderer_jellyfin_apt_key_path }}"
  register: apt_key_status
- name: Download apt repo key
  ansible.builtin.get_url:
    url: "{{ renderer_jellyfin_apt_key_url }}"
    dest: "/tmp/jellyfin.gpg"
    mode: '0600'
  when: not apt_key_status.stat.exists
- name: Install/convert apt repo key
  ansible.builtin.command:
    cmd: "/usr/bin/gpg -o '{{ renderer_jellyfin_apt_key_path }}' --dearmor '/tmp/jellyfin.gpg'"
    creates: "{{ renderer_jellyfin_apt_key_path }}"
  when: not apt_key_status.stat.exists
  become: true
- name: Add apt repo
  ansible.builtin.template:
    src: aptsource.list.j2
    dest: "/etc/apt/sources.list.d/jellyfin.list"
    owner: root
    group: root
    mode: '0644'
  notify: Apt update
  become: true
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
- name: Install ffmpeg
  ansible.builtin.apt:
    name: jellyfin-ffmpeg7
    state: present
  become: true
