---
- name: Cleanup Exploded WARs
  ansible.builtin.file:
    path: "{{ guacamole_tomcat_install_root }}/webapps/{{ item }}"
    state: absent
  loop:
    - ROOT
    - guacamole
    - guacamole.war
- name: Restart Tomcat
  ansible.builtin.service:
    name: tomcat
    state: restarted
- name: Restart guacd
  ansible.builtin.service:
    name: guacd
    state: restarted
- name: Run ldconfig
  ansible.builtin.command:
    cmd: ldconfig
  changed_when: false
