---
proxy_port: 9000
reverseproxy_nginx_after:
  - network-online.target
  - thelounge.service
proxy_healthcheck:
  path: /health
  checks:
    - type: port
      value: "{{ proxy_port }}"
    - type: service
      value: thelounge
