---
redis_cluster_name: brnet-home-redis
redis_port: 6379
redis_sentinel_port: 26379

redis_requirepass: "{{ vault_redis_requirepass }}"
redis_masterauth: "{{ vault_redis_requirepass }}"

redis_sentinel_quorum: 2
redis_sentinel_down_after_milliseconds: 5000
redis_sentinel_failover_timeout: 60000
redis_sentinel_parallel_syncs: 1
