---
authelia_repo_source: "authelia/authelia"
authelia_version: "4.39.20"
authelia_checksum: "sha256:1f122add61752d6ef54e64ae7116bec4e026f5c0a6493498288c5a9770d92088"

authelia_user: "authelia"
authelia_config_path: "/etc/authelia"
authelia_config_file: "{{ authelia_config_path }}/configuration.yml"

authelia_install_root: "/opt/authelia"
authelia_version_dir: "{{ authelia_install_root }}/{{ authelia_version }}"
authelia_bin_path: "/usr/local/bin/authelia"

authelia_host: "127.0.0.1"
authelia_port: 9091

authelia_database_port: 3306

authelia_log_level: "info"

authelia_session_name: "authelia_session"
authelia_session_expiration: "1h"
authelia_session_inactivity: "5m"
authelia_session_remember_me_duration: "1M"

authelia_session_redis_host: "127.0.0.1"
authelia_session_redis_port: 6379
authelia_session_redis_username: "authelia"
authelia_session_redis_password: ""
authelia_session_redis_tls_enabled: false

authelia_oidc_enabled: false
authelia_oidc_hmac_secret: ""
authelia_oidc_issuer_private_key: ""
authelia_oidc_authorization_policies: {}
authelia_oidc_clients: []
