---
- name: Install IPA Client (apt)
  ansible.builtin.apt:
    name: "ipa-client"
    state: "present"
  become: true
  when: ansible_os_family == "Debian"
- name: Install IPA Client (dnf)
  ansible.builtin.dnf:
    name: "ipa-client"
    state: "present"
  become: true
  when: ansible_os_family == "RedHat"
- name: Check domains
  ansible.builtin.command:
    cmd: "sssctl domain-list"
  changed_when: false
  become: true
  register: domain_list
