---
certbot_certs:
  - ["{{ inventory_hostname }}"]

valkey_proxy_port: 6379
valkey_proxy_tls: yes
valkey_proxy_cluster_username: valkeyproxy
valkey_proxy_cluster_password: "{{ valkey_valkeyproxy_password }}"
