---
- name: Get Cargo.toml local stat
  ansible.builtin.stat:
    path: "{{ role_path }}/files/redis_prefix_rewrite_wasm/Cargo.toml"
  delegate_to: localhost
  become: false
  register: cargo_toml_local_stat
  run_once: true
- name: Get lib.rs local stat
  ansible.builtin.stat:
    path: "{{ role_path }}/files/redis_prefix_rewrite_wasm/src/lib.rs"
  delegate_to: localhost
  become: false
  register: lib_rs_local_stat
  run_once: true
- name: Calculate combined source hash
  ansible.builtin.set_fact:
    wasm_src_hash: "{{ (cargo_toml_local_stat.stat.checksum + lib_rs_local_stat.stat.checksum) | ansible.builtin.hash('sha256') }}"
- name: Ensure base WASM directories exist on remote host
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ shotover_user }}"
    group: "{{ shotover_group }}"
    mode: '0755'
  loop:
    - "/opt/shotover/wasm_transforms"
    - "/opt/shotover/wasm_transforms/{{ wasm_src_hash }}"
- name: Check if this version of WASM is already built on remote host
  ansible.builtin.stat:
    path: "/opt/shotover/wasm_transforms/{{ wasm_src_hash }}/redis_prefix_rewrite_wasm.wasm"
  register: wasm_file_stat
- name: Include local WASM build tasks
  ansible.builtin.include_tasks: wasm_build_local.yml
  when:
    - not wasm_file_stat.stat.exists
    - shotover_wasm_build_location | default('localhost') == 'localhost'
- name: Include remote WASM build tasks
  ansible.builtin.include_tasks: wasm_build_remote.yml
  when:
    - not wasm_file_stat.stat.exists
    - shotover_wasm_build_location | default('localhost') == 'remote'
- name: Create symlink in Shotover topology directory
  ansible.builtin.file:
    src: "/opt/shotover/wasm_transforms/{{ wasm_src_hash }}/redis_prefix_rewrite_wasm.wasm"
    dest: "{{ shotover_topology_dir }}/redis_prefix_rewrite_wasm.wasm"
    state: link
    owner: "{{ shotover_user }}"
    group: "{{ shotover_group }}"
    force: true
  notify: Restart Shotover
