---
- name: Create HomeBox env file
  ansible.builtin.template:
    src: env.j2
    dest: /opt/.env
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Restart HomeBox
- name: Ensure HomeBox is running and enabled
  ansible.builtin.service:
    name: homebox
    state: started
    enabled: true
  become: true
