---
- name: Check apt repo key
  ansible.builtin.stat:
    path: "{{ sspasswd_apt_key_path }}"
  register: apt_key_status
- name: Download apt repo key
  ansible.builtin.get_url:
    url: "{{ sspasswd_apt_key_url }}"
    dest: "/tmp/ltb-project.gpg"
    mode: '0600'
  when: not apt_key_status.stat.exists
- name: Install/convert apt repo key
  ansible.builtin.command:
    cmd: "/usr/bin/gpg -o '{{ sspasswd_apt_key_path }}' --dearmor '/tmp/ltb-project.gpg'"
    creates: "{{ sspasswd_apt_key_path }}"
  when: not apt_key_status.stat.exists
  become: true
- name: Add apt repo
  ansible.builtin.template:
    src: aptsource.list.j2
    dest: "/etc/apt/sources.list.d/ltb-project.list"
    owner: root
    group: root
    mode: '0644'
  notify: Apt update
  become: true
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
- name: Install SSP
  ansible.builtin.apt:
    name: self-service-password
    state: present
  when: ansible_os_family == "Debian"
  become: true
