---
- name: Apt install
  ansible.builtin.include_tasks:
    file: aptinstall.yml
  when: ansible_os_family == "Debian"
- name: Web Config
  ansible.builtin.include_tasks:
    file: webconfig.yml
- name: SSP App config
  ansible.builtin.template:
    src: config.inc.local.php.j2
    dest: "/etc/self-service-password/config.inc.local.php"
    owner: root
    group: root
    mode: '0644'
  become: true
- name: Check audit log permissions
  ansible.builtin.stat:
    path: "{{ sspasswd_audit_log_file }}"
  register: audit_log_stat
  become: true
- name: Ensure audit log permissions
  ansible.builtin.file:
    path: "{{ sspasswd_audit_log_file }}"
    state: touch
    owner: "www-data"
    group: root
    mode: '0640'
  when: audit_log_stat.stat.exists or audit_log_stat.stat.mode != '0640' or audit_log_stat.stat.pw_name != "www-data"
  become: true
