---
- name: Uninstall Apache # This gets installed by SSP
  ansible.builtin.apt:
    name: apache2
    state: absent
  become: true
- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present
  become: true
- name: Generate dhparams file
  ansible.builtin.command:
    cmd: "openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048"
    creates: "/etc/ssl/certs/dhparam.pem"
  become: true
  notify: Restart Nginx
- name: SSL Config
  ansible.builtin.copy:
    src: ssl.conf
    dest: /etc/nginx/snippets/ssl.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Restart Nginx
- name: Nginx Site Available (default)
  ansible.builtin.template:
    src: nginxsite.conf.j2
    dest: "/etc/nginx/sites-available/default"
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Restart Nginx
- name: Nginx Site Enabled (default)
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/default"
    dest: "/etc/nginx/sites-enabled/default"
    state: link
    owner: root
    group: root
    mode: '0755'
- name: "Certbot Deploy Script"
  ansible.builtin.copy:
    src: certbot-deploy-hook.sh
    dest: /etc/letsencrypt/renewal-hooks/deploy/nginx.sh
    owner: root
    group: root
    mode: '0755'
  become: true
- name: Ensure Nginx is running
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  become: true
