---
valkey_port: 6379
valkey_cluster_enabled: yes
valkey_appendonly: yes
valkey_appendfsync: everysec

valkey_users:
  - username: authelia
    password: "{{ valkey_authelia_password }}"
    acl: "~authelia:* +@all -@dangerous"
  - username: valkeyproxy
    password: "{{ valkey_valkeyproxy_password }}"
    acl: "+@all"
