---
- name: Install Keepalived
  ansible.builtin.package:
    name: keepalived
    state: present
  become: true
- name: Needed scripts
  ansible.builtin.set_fact:
    keepalived_check_scripts_needed: "{{ keepalived_check_scripts | dict2items | json_query('[].value.type') | list | unique }}"
- name: HAProxy Backend Tracking Script
  ansible.builtin.copy:
    src: haproxy_track.sh
    dest: /usr/local/bin/haproxy_track.sh
    owner: root
    group: root
    mode: '0755'
  become: true
  when: "'haproxy' in keepalived_check_scripts_needed"
- name: Remove HAProxy Backend Tracking Script if not used
  ansible.builtin.file:
    path: /usr/local/bin/haproxy_track.sh
    state: absent
  become: true
  when: "'haproxy' not in keepalived_check_scripts_needed"
- name: VIP Absent Script
  ansible.builtin.copy:
    src: vip_check_absent.sh
    dest: /usr/local/bin/vip_check_absent.sh
    owner: root
    group: root
    mode: '0755'
  become: true
  when: "'vip_absent' in keepalived_check_scripts_needed"
- name: Remove VIP Absent Script if not used
  ansible.builtin.file:
    path: /usr/local/bin/vip_check_absent.sh
    state: absent
  become: true
  when: "'vip_absent' not in keepalived_check_scripts_needed"
- name: Create Keepalived configuration file from template
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Restart Keepalived
- name: Ensure Keepalived is running and enabled
  ansible.builtin.service:
    name: keepalived
    state: started
    enabled: true
  become: true
