---
- name: HAProxy Certbot Deploy
  ansible.builtin.command:
    cmd: "{{ haproxy_certbot_deploy_hook }}"
  changed_when: true
  become: true
- name: Restart HAProxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
  become: true
