---
common_join_ipa_domain: false

ansible_ssh_common_args: '-o ProxyJump={{ ansible_user | default(lookup("env", "USER")) }}@bastion01.usw2.aws.brwyatt.net'

chrony_sources:
  - type: "server"
    location: "169.254.169.123"
    iburst: true
    trust: true
    prefer: true
