---
pxe_vip: "172.17.30.202"
cephclient_mon_dns_srv_name:
  domain: "home.brwyatt.net"
cephclient_mounts:
  - user: pxe
    fs_name: "DisklessFS"
    remote_path: "/boot"
    mount_path: "{{ pxeserver_boot_dir }}"
pxeserver_boot_dir: "/mnt/diskless_boot"
pxeserver_ip: "{{ pxe_vip }}"
pxeserver_hostname: "pxe.home.brwyatt.net"
pxeserver_pxe_hosts:
  - name: pxe-boot-test
    uuid: "${pxe_boot_test_uuid}"
    ipxe_path: "/_iPXE/test.ipxe"
    kernel_path: "/Zephyr/vmlinuz"
    initrd_path: "/Zephyr/initrd.img"
  - name: Zephyr
    uuid: "${zephyr_uuid}"
    ipxe_path: "/_iPXE/ubuntu/noble.ipxe"
    kernel_path: "/Zephyr/vmlinuz"
    initrd_path: "/Zephyr/initrd.img"
keepalived_check_scripts:
  nginx:
    insecure: true
    url: "http://127.0.0.1/check"
    type: curl
  tftp:
    insecure: true
    url: "tftp://127.0.0.1/boot.ipxe"
    type: curl
  pxemount:
    type: mount
    path: "{{ pxeserver_boot_dir }}"
keepalived_instances:
  pxe:
    virtual_ip: "{{ pxe_vip }}/24"
    auth_pass: "{{ keepalived_auth_pass }}"
    check_scripts:
      - nginx
      - tftp
      - pxemount
