---
- name: Users
  ansible.builtin.include_role:
    role: users
  vars:
    users_include: "{{ ['localadmin'] if common_join_ipa_domain else 'all' }}"
- name: Manage Apt
  ansible.builtin.include_tasks:
    file: apt.yml
  when: ansible_os_family == "Debian"
- name: Manage Chrony
  ansible.builtin.include_role:
    role: chrony
- name: Join Domain
  ansible.builtin.include_role:
    role: freeipa.ansible_freeipa.ipaclient
  when: common_join_ipa_domain
- name: Manage SSH service
  ansible.builtin.include_tasks:
    file: sshd.yml
- name: Install common packages (apt)
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  become: true
  when: ansible_os_family == "Debian"
  loop:
    - vim
    - htop
- name: Install common packages (dnf)
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  become: true
  when: ansible_os_family == "RedHat"
  loop:
    - vim
    - htop
- name: Qemu guest agent
  ansible.builtin.include_tasks:
    file: qemu-guest-agent.yml
  when: ansible_virtualization_role == "guest" and ansible_system_vendor == "QEMU"
- name: Manage /etc/hosts
  ansible.builtin.include_tasks:
    file: etc_hosts.yml
  when: common_manage_etc_hosts
