---
- name: Users
  ansible.builtin.include_role:
    role: users
- name: Manage Apt
  ansible.builtin.include_tasks:
    file: apt.yml
- name: Manage SSH service
  ansible.builtin.include_tasks:
    file: sshd.yml
- name: Ensure vim is installed
  ansible.builtin.apt:
    name: vim
    state: present
  become: true
- name: Ensure htop is installed
  ansible.builtin.apt:
    name: htop
    state: present
  become: true
- name: Install qemu-guest-agent on Qemu VMs
  ansible.builtin.apt:
    name: qemu-guest-agent
    state: present
  become: true
  when: ansible_virtualization_role == "guest" and ansible_system_vendor == "QEMU"
