---
- name: Set Admin Password
  ansible.builtin.user:
    name: "{{ common_admin_user }}"
    password: "{{ common_admin_password }}"
  become: true
- name: Manage Admin SSH Keys
  ansible.builtin.authorized_key:
    user: "{{ common_admin_user }}"
    key: "{{ (common_admin_keys|default([]))|join('\n') }}"
    exclusive: true
    manage_dir: true
  become: true
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400 # Check cache at most once per day (in seconds)
- name: Ensure vim is installed
  ansible.builtin.apt:
    name: vim
    state: present
- name: Ensure htop is installed
  ansible.builtin.apt:
    name: htop
    state: present
- name: Install qemu-guest-agent on Qemu VMs
  ansible.builtin.apt:
    name: qemu-guest-agent
    state: present
  become: true
  when: ansible_virtualization_role == "guest" and ansible_system_vendor == "QEMU"
