---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400 # Check cache at most once per day (in seconds)
- name: Ensure vim is installed
  ansible.builtin.apt:
    name: vim
    state: present
