---
- name: Install qemu-guest-agent on Qemu VMs (apt)
  ansible.builtin.apt:
    name: qemu-guest-agent
    state: present
  become: true
  when: ansible_os_family == "Debian"
- name: Install qemu-guest-agent on Qemu VMs (dnf)
  ansible.builtin.dnf:
    name: qemu-guest-agent
    state: present
  become: true
  when: ansible_os_family == "RedHat"
