---
- name: Ensure ssh is installed
  ansible.builtin.apt:
    name: ssh
    state: present
  become: true
- name: Start sshd
  ansible.builtin.service:
    name: ssh
    state: started
    enabled: true
  become: true
