---
- name: Ensure ssh server is installed (apt)
  ansible.builtin.apt:
    name: ssh
    state: present
  become: true
  when: ansible_os_family == "Debian"
- name: Ensure ssh server is installed (dnf)
  ansible.builtin.dnf:
    name: openssh-server
    state: present
  become: true
  when: ansible_os_family == "RedHat"
- name: Configure sshd
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^\\s*#?\\s*{{ item.key }}\\s"
    line: "{{ item.key }} {{ item.value }}"
    state: present
    validate: "/usr/sbin/sshd -t -f %s"
  loop:
    - { key: "PermitRootLogin", value: "{{ common_ssh_permit_root_login }}" }
    - { key: "PasswordAuthentication", value: "no" }
    - { key: "PubkeyAuthentication", value: "yes" }
    - { key: "Ciphers", value: "{{ common_ssh_ciphers | join(',') }}" }
    - { key: "KexAlgorithms", value: "{{ common_ssh_kexalgorithms | join(',') }}" }
    - { key: "MACs", value: "{{ common_ssh_macs | join(',') }}" }
  notify: Restart sshd
- name: Flush Handlers
  ansible.builtin.meta: flush_handlers
- name: Start sshd
  ansible.builtin.service:
    name: |-
      {{
        common_sshd_service_name |
        default(
          common_sshd_service_name_families[ansible_os_family] |
          default('sshd')
        )
      }}
    state: started
    enabled: true
  become: true
