---
haproxy_frontends:
  redis-sentinel:
    mode: tcp
    bind:
      port: 26379
    backend: redis-sentinel-backend
haproxy_backends:
  redis-sentinel-backend:
    mode: tcp
    balance: roundrobin
    options:
      - "option tcp-check"
      - "tcp-check connect"
      - "tcp-check send PING\r\n"
      - "tcp-check expect string +PONG"
      - "server-template sentinel 1-3 _sentinel._tcp.redis.server.home.brwyatt.net resolvers localdns init-addr none"
keepalived_instances:
  redis:
    virtual_ip: "172.17.30.211/24" # Assuming next available VIP
    auth_pass: "{{ keepalived_auth_pass }}"
    check_scripts:
      - haproxy
