---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400 # Check cache at most once per day (in seconds)
- name: Ensure vim is installed
  apt:
    name: vim
    state: present
