---
authelia_repo_source: "brwyatt/authelia"
authelia_version: "4.39.19-RedisKeyPrefix"
authelia_checksum: "sha256:a90638069a533fc0ec3f8ababbb794a640b67b911ce474fe51399ed5f59f4f1a"

authelia_session_domain: "home.brwyatt.net"
authelia_session_redis_host: "valkey.server.home.brwyatt.net"
authelia_session_redis_password: "{{ valkey_authelia_password }}"
authelia_session_redis_tls_enabled: true
authelia_session_redis_key_prefix: "{authelia-session}"

authelia_ldap_url: "ldaps://ipa.home.brwyatt.net"
authelia_ldap_base_dn: "dc=home,dc=brwyatt,dc=net"
authelia_ldap_user: "uid=authelia,cn=users,cn=accounts,{{ authelia_ldap_base_dn }}"

authelia_database_type: "mysql"
authelia_database_host: "mariadb.server.home.brwyatt.net"
authelia_database_name: "authelia"
authelia_database_user: "authelia"

authelia_access_control_rules:
  - domain: "seedbox.server.home.brwyatt.net"
    policy: "one_factor"
    subject: "group:seedboxusers"

proxy_port: 9091

reverseproxy_trusted_proxies:
  - "172.17.30.121"
  - "172.17.30.172"
