---
aws_creds_role_arn: "CHANGEME"
authelia_session_secret: "CHANGEME"
authelia_jwt_secret: "CHANGEME"
authelia_storage_encryption_key: "CHANGEME"
authelia_ldap_password: "CHANGEME"
authelia_database_password: "CHANGEME"
