---
openterminal_user: "agent-homelab-sre"
openterminal_group: "agent-homelab-sre"
openterminal_version: "latest"
openterminal_host: "127.0.0.1"
openterminal_port: 8000
openterminal_api_key: ""
openterminal_working_dir: ""
openterminal_install_dir: "/opt/openterminal"
openterminal_venv_dir: "{{ openterminal_install_dir }}/venv"

# Extra Environment configuration (if any needed for OpenTerminal)
openterminal_extra_env: {}
